- name: Add Varnish Plus 6.0 repo
  block:
    - set_fact:
        varnish_repo_key_url: https://{{ settings['varnish-plus'].user }}@packagecloud.io/varnishplus/60/gpgkey

    - name: Add Varnish Plus repo key
      shell: |
        set -e
        curl -L {{ varnish_repo_key_url }} | apt-key add -
        touch /home/vagrant/.vagrant.varnish.add-varnish-plus-repo-key
      args:
        creates: /home/vagrant/.vagrant.varnish.add-varnish-plus-repo-key

    - name: Add Varnish Plus repo
      apt_repository:
        filename: varnish-plus
        repo: deb https://{{ settings['varnish-plus'].user }}:@packagecloud.io/varnishplus/60/ubuntu/ xenial main
        update_cache: True

- name: Install Varnish packages
  notify:
    - restart-varnish
    - restart-vha-agent
  apt:
    name:
      - varnish-plus
      - varnish-plus-ha
    update_cache: True

- name: Create VCP nodes.conf
  notify:
    - restart-vha-agent
  copy:
    dest: /etc/varnish/nodes.conf
    content: |
      localhost = 127.0.0.1:6081

- name: Configure VHA Agent
  block:
    - name: Create folder to override VHA Agent unit
      file:
        path: /etc/systemd/system/vha-agent.service.d/
        state: directory

    - name: Create override.conf for VHA Agent unit
      notify: restart-vha-agent
      register: set_vha_agent_unit
      copy:
        dest: /etc/systemd/system/vha-agent.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/vha-agent \
              -D \
              -t off \
              -P /run/vha-agent/vha-agent.pid \
              -m localhost \
              -p stat_intvl=1 \
              -N /etc/varnish/nodes.conf -s /var/lib/vha-agent/vha-status -T s3cr3t

    - name: Execute systemctl daemon-reload
      when: set_vha_agent_unit.changed
      systemd:
        daemon_reload: yes
